### PR TITLE
Fixing coverage report generation

### PR DESCRIPTION
**Pull request by stevepeak**
Please don't merge till we confirm coverage is reporting properly. Thank you :+1:

### CODE REVIEW

**Comment by stevepeak** [comment]
Are there any tests written for this project yet?

**Comment by furknyavuz** [comment]
Hi steve not have. But let me create dummy.

**Comment by furknyavuz** [comment]
Added simple dummy test to master. Trying again.

**Comment by furknyavuz** [comment]
Oh cool! That is the problem. If you don't have any tests jacoco can't generate .exec file. Problem solved Steve thank you :+1:

**Comment by stevepeak** [comment]
You are very welcome :)

**Pull request closed without merging**
